spring:
  profiles:
    active: dev
    include: feign
  application:
    name: mall-service-product
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        namespace: dev
        username: nacos
        password: nacos

server:
  port: 9002
---
spring:
  config:
    activate:
      on-profile: test
    import:
      - nacos:common.yaml?group=mall-service-product
      - nacos:datasource.yaml?group=mall-service-product

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:common.yaml?group=mall-service-product
      - nacos:datasource.yaml?group=mall-service-product

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - nacos:common.yaml?group=mall-service-product
      - nacos:datasource.yaml?group=mall-service-product

