spring:
  profiles:
    active: dev
    include: feign
  application:
    name: mall-service-payment
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        namespace: dev
        username: nacos
        password: nacos

jwt:
  secret: Ai+QwjUslNR6e0NXAcvbhv4LxGsLqkMlrq980le2VDPuwc+USgBW59fnAg9+

server:
  port: 7000


logging:
  level:
    com.hyx.order.feign: debug
---
spring:
  config:
    activate:
      on-profile: test
    import:
      - nacos:common.yaml?group=mall-service-payment
      - nacos:datasource.yaml?group=mall-service-payment

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:common.yaml?group=mall-service-payment
      - nacos:datasource.yaml?group=mall-service-payment

---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - nacos:common.yaml?group=mall-service-payment
      - nacos:datasource.yaml?group=mall-service-payment

