spring:
  profiles:
    active: dev
    include: feign
  application:
    name: mall-service-order
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        namespace: dev
        username: nacos
        password: nacos
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 9003

# 支付超时自动取消阈值（分钟）
order:
  pay-timeout-minutes: 30
---
spring:
  config:
    activate:
      on-profile: test
    import:
      - nacos:common.yaml?group=mall-service-order
      - nacos:datasource.yaml?group=mall-service-order

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:common.yaml?group=mall-service-order
      - nacos:datasource.yaml?group=mall-service-order


---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - nacos:common.yaml?group=mall-service-order
      - nacos:datasource.yaml?group=mall-service-order

