spring:
  profiles:
    active: dev
    include: feign
  application:
    name: mall-service-order
  cloud:
    nacos:
      server-addr: localhost:8848
      username: nacos
      password: nacos
      config:
        namespace: dev
        username: nacos
        password: nacos

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

server:
  port: 6000


logging:
  level:
    com.hyx.order.feign: debug
---
spring:
  config:
    activate:
      on-profile: test
    import:
      - nacos:common.yaml?group=mall-service-order
      - nacos:datasource.yaml?group=mall-service-order

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - nacos:common.yaml?group=mall-service-order
      - nacos:datasource.yaml?group=mall-service-order


---
spring:
  config:
    activate:
      on-profile: prod
    import:
      - nacos:common.yaml?group=mall-service-orer
      - nacos:datasource.yaml?group=mall-service-order

